<?php
require('hero-section.php');
require('accreditation-section.php');
//require('testimonial-section.php');
require('commons.php');
require('user-extra-fields-handling.php');
require('color-settings.php');
require('custom-contact.php');
require('email_notification.php');
require('rewards.php');
require('authorize-payment-settings.php');
require('control-course-transient.php');
require('groupDiscount.php');
require('init-header-menu.php');