<?php
require('hero-section.php');
require('testimonial-section.php');
require('commons.php');
require('user-extra-fields-handling.php');
require('color-settings.php');
require('custom-contact.php');
require('email_notification.php');
require('init_email_notification_db.php');
require('rewards.php');
require('redis-cache-settings.php');