<?php
require_once('init_static_pages.php');
require_once('init_ce.php');
require_once('init_db.php');
require_once('init_email_notification_db.php');
require_once('import_init_files.php');
require_once('init_category_difficulty.php');
require_once('init_certificate_template.php');
require_once('init_survey_author_proposal.php');
